name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install TA-Lib from source
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential wget unzip
          wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
          tar -xzf ta-lib-0.4.0-src.tar.gz
          cd ta-lib
          ./configure --prefix=/usr
          make
          sudo make install
          sudo ldconfig

      - name: Install dependencies
        run: |
          export LD_LIBRARY_PATH=/usr/lib:$LD_LIBRARY_PATH
          pip install -r requirements.txt
      - name: Run tests
        run: python --version
     
